model = "gpt-5.1-codex-max"
model_provider = "openai-chat-completions"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "high"

[model_providers.openai-chat-completions]
name = "OpenAI GPT-5 Codex"
model = "gpt-5.1-codex-max"
base_url = "https://api.openai.com.proxy.vibecodeapp.com/v1"
env_key = "OPENAI_API_KEY"
preferred_auth_method = "apikey"
approval_policy = "never"
hide_agent_reasoning = false
tools.web_search = true
wire_api = "responses"

[projects."/home/vibecode/workspace"]
trust_level = "trusted"
